### ISSUE TITLE
Going into standby issue

### ISSUE THREAD

**Issue by BenDinsdale** [mcubemems/mCube_mc34x9_arduino_driver#3]
Hello,

I'm working on a C library for the MC3419 as my project doesn't support C++. 
I have been using your library for reference as some of the registers are missing from the data sheet mainly the device ID register

whilst I have been writing my library I have spotted a mistake in the enumeration used by the SetMode function:

typedef enum
{
  MC34X9_MODE_SLEEP    = 0b000,
  MC34X9_MODE_CWAKE      = 0b001,
  MC34X9_MODE_RESERVED   = 0b010,
  MC34X9_MODE_STANDBY  = 0b011,
}   MC34X9_mode_t;

According to the datasheet the MC34X9 only has two states: standby (0), and wake (1).
MC34X9_MODE_STANDBY is used in various functions in the ".cpp" file

Best regards
Ben

**Comment by pmancele** [comment]
Hello,

Did you manage to get it working ? The driver compiles fine on my side, I got I2C acknowledge but the sensor doesn't work properly..

**Comment by BenDinsdale** [comment]
The Arduino driver code works fine as is.
I bought a licenced version of the MC3419 from MEMSIC, and their version of the datasheet at V1.1 has several mistakes in the operational description and in the registers, the latest MC34X9 datasheet on mCube's website still has the mistakes in the operational description but the register information is correct and matches this library.

**Comment by pmancele** [comment]
Ok thanks you for your answer.
I am working on the MC3416 on my side so I used the official driver (https://github.com/mcubemems/mCube_mc34x6_mcu_driver). But there is also differences between the datasheet and the driver definitions (STANDBY register for exemple). 
Whatever the mode we put the sensor on, he ACKNOWLEDGE our i2c requests but always answers 0x00 or 0x80.. Even when reading the CHIPID register or a register we juste wrote into ..
Maybe it was soldered with too hot air and is broken.
I can't find any explanation and we have the case on multiple boards

**Comment by BenDinsdale** [comment]
Hello,

Just had a quick look at the datasheet for the MC3416 on the mCube website, its at version V2.0 (preliminary) 2018
Mouser has a more resent V2.1 2020, although its branded as memSIC, you might find some differences their:
[https://www.mouser.co.uk/datasheet/2/821/20200827164815098-2581447.pdf](url) 

Just using the .ino for the MC34X9 devices you should be able to read back the device ID without issue as its in the same register address, although it wont match what the code is expecting, this may help you determine if its a software or hardware issue?

Are you using hardware or software I2C? If its the latter its common to have read back issues.
you normally have to do a little bit of tweaking to the software I2C's read function's timing to ensure that the bit is read back  half way or just past half way through the clock pulse. 

If its Hardware I2C, I'd check the basics ensure your pull ups are fitted correctly, and an appropriate value (4K7-10K), look for bridges on the IC etc. I'd also ensure you haven't accidently enabled pull up or pull downs in your software.

Best regards
Ben

**Comment by pmancele** [comment]
Thank you for your good advices but we already tested thoose things :)

4.7 k pull ups, hardware I2C (on a STM32L4A6RG), clock and SDA are beautiful on the scope and we can see that the sensor ACK on I2C but then responds with non-sense frames.

Tested with the official driver and a driver wrote by myself. I will try some others things and keep you in touch, but i'm running out of ideas ^^

Thank you for the datasheet ! Indeed the mouser is more recent. But still indicates : 

![image](https://user-images.githubusercontent.com/25764849/166908196-f32226f4-fad6-4846-899c-e4356410f2a9.png)

While in the code there is : 

```c++
/* Available mode in MC34X6 sensor */
typedef enum
{
    E_M_DRV_MC34X6_MODE_SLEEP = 0x00,
    E_M_DRV_MC34X6_MODE_WAKE,
    E_M_DRV_MC34X6_MODE_RESERVED,        //Reserve, not use
    E_M_DRV_MC34X6_MODE_STANDBY,
    E_M_DRV_MC34X6_MODE_END,

    E_M_DRV_MC34X6_INTR_IPP_OPEN_DRAIN_IAH_LOW      =   0,       //External pullup to VDD for INT and active low
    E_M_DRV_MC34X6_INTR_IPP_MODE_PUSH_PULL_IAH_LOW  =   0x40,    //Logic high drive level is VDD for INT and active low
    E_M_DRV_MC34X6_INTR_IPP_OPEN_DRAIN_IAH_HIGH     =   0x80,    //External pullup to VDD for INT and active high
    E_M_DRV_MC34X6_INTR_IPP_MODE_PUSH_PULL_IAH_HIGH =   0xC0,    //Logic high drive level is VDD for INT and active high
    E_M_DRV_MC34X6_INTR_END,
}   e_m_drv_mc34x6_mode_t;
```
